# Alex Aalbertsberg
# Jasper ter Weeme

all:
	cd bsp && ./create-this-bsp
	make -C zuul1

clean:
	rm -Rvf bsp/Makefile bsp/*.c bsp/*.h bsp/*.html bsp/drivers bsp/HAL bsp/obj bsp/*.mk bsp/*.x bsp/*.a bsp/*.gdb

